feat: added plugin to search for xdg user directories
Kirottu/anyrun pull request #73
Opened 2023-08-05 20:05 UTC by abenz1267

Hi,

this plugin would allow you to use anyrun to search/open xdg user directories, see [here](https://wiki.archlinux.org/title/XDG_user_directories).

What do you think? Personally i use the finder rather often in order to open those directories.

Regards

2023-08-05 23:02 UTC, Kirottu commented
It feels a bit redundant as the Kidex plugin already achieves file/folder search.

Also, is that `~/.config/user-dirs.dirs` a standard file?

2023-08-06 06:14 UTC, abenz1267 commented
> It feels a bit redundant as the Kidex plugin already achieves file/folder search.

I actually tried the Kidex plugin before i created this and my reasons where:
- i don't need filesearch
- i don't want to have a background process running for something as simple as looking up user directories
- i wanted something really tiny in scope

> Also, is that `~/.config/user-dirs.dirs` a standard file?

Yes, it's the default file for xdg-user-dir.

If you feel like this is redundant and you don't want it in here, that's no problem. I just thought other people might be interested as well.

Regards

2023-08-06 17:32 UTC, Kirottu commented
Having an entire plugin just for this purpose seems a bit redundant, a general shortcut plugin would probably be more useful in my opinion.

2023-08-06 17:42 UTC, abenz1267 commented
> Having an entire plugin just for this purpose seems a bit redundant, a general shortcut plugin would probably be more useful in my opinion.

I thought about that as well, but then you'd either: 
a) need to implement logic to find shortcuts/bookmarks for different "platforms", e.g. nautilus saves bookmarks in a different place then dolphin
b) need to define the shortcuts in a config file for the plugin

But now if you use xdg-user-dirs anyways and define commonly used folders there as well already, you are kinda doing double the work. I'm not sure.

My original intent was indeed to just search for nautilus bookmarks. But going the xdg-user-dirs approach looked saner in my eyes, as it's independent from any installed filebrowser gui.

Regards

2023-08-06 17:50 UTC, Kirottu commented
I'd lean towards configuring shortcuts inside a config file, then `xdg-open` could be used to open them so you could add shortcuts to basically anything you wish.

2023-08-16 19:08 UTC, Sntx626 requested changes
I'd like to see a backup in case `~/.config/user-dirs.dirs` is not present.

The hard-to-read part of the code (look at my other comments) should be simplified.

Overall this plugin might be redundant with kidex, but yet again not everyone is running kidex. So it's still a viable plugin.

2023-08-16 19:08 UTC, Sntx626 commented on plugins/userdirs/src/lib.rs
> +    }
I feel like this whole construct could be simplified a lot by using iters. It is hard to read as it is right now.

Try using filter_map here as well!

2023-08-16 19:08 UTC, Sntx626 commented on plugins/userdirs/src/lib.rs
> +            if let Ok(lines) = read_lines(format!("{}/.config/user-dirs.dirs", path.display())) {
Not sure if this is present on every system. It is present on mine (auto-generated by nix).

2024-02-24 09:02 UTC, closed without merging